__title__ = 'eve-azure-ad-auth'
__description__ = ''
__url__ = 'https://github.com/ateliedocodigo/eve-azure-ad-auth'
__version__ = '0.0.0'
__author__ = 'LuisComS'
__author_email__ = 'luiscoms@ateliedocodigo.com.br'
__copyright__ = 'Copyright 2020 Ateliê do Código'
